import type { Metadata } from "next";
import { Hanken_Grotesk, Instrument_Serif, DM_Mono } from "next/font/google";
import { NavBar } from "./components/";
import "./globals.css";

export const hankenGrotesk = Hanken_Grotesk({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-hanken-grotesk",
});

export const instrumentSerif = Instrument_Serif({
  weight: "400",
  variable: "--font-instrument-serif",
  subsets: ["latin"],
});

export const dmMono = DM_Mono({
  weight: ["300", "400", "500"],
  subsets: ["latin"],
  variable: "--font-dm-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${hankenGrotesk.variable} ${instrumentSerif.variable} ${dmMono.variable} dark:bg-greyscale-950 dark:text-greyscale-50 antialiased`}
      >
        <NavBar />
        {children}
      </body>
    </html>
  );
}
