import type { Metadata } from "next";
import { Hanken_Grotesk, Instrument_Serif, DM_Mono } from "next/font/google";
import { NavBar } from "./components/";
import { ScrollToTop } from "./hooks";
import "./globals.css";

export const hankenGrotesk = Hanken_Grotesk({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-hanken-grotesk",
});

export const instrumentSerif = Instrument_Serif({
  weight: "400",
  style: ["normal", "italic"],
  variable: "--font-instrument-serif",
  subsets: ["latin"],
});

export const dmMono = DM_Mono({
  weight: ["300", "400", "500"],
  subsets: ["latin"],
  variable: "--font-dm-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${hankenGrotesk.variable} ${instrumentSerif.variable} ${dmMono.variable} bg-greyscale-100 dark:bg-greyscale-900 dark:text-greyscale-100 mx-auto grid auto-rows-min grid-cols-1 place-items-center antialiased`}
      >
        <ScrollToTop />
        <NavBar />
        <main className="grid max-w-7xl grid-cols-4 gap-3 px-3 md:grid-cols-8 md:gap-4 md:px-6 lg:grid-cols-12 lg:px-8">
          {children}
        </main>
      </body>
    </html>
  );
}
